export const ADMIN_AUTH_GROUP = 'Auth'
export const CUSTOMER_ROLE_SLUG = 'customer' as const
export const POST_SLUG = 'posts' as const
export const POST_TAG_SLUG = 'post-tags' as const
export const USER_SLUG = 'users' as const
export const ORDER_SLUG = 'orders' as const
export const PRODUCT_SLUG = 'products' as const
export const PRODUCT_COLLECTION_SLUG = 'product-collections' as const
export const PAGE_SLUG = 'pages' as const
export const MEDIA_SLUG = 'media' as const
export const PRODUCT_CATEGORY_SLUG = 'product-categories' as const
export const BLOG_CATEGORY_SLUG = 'blog-categories' as const
// export const SHOP_COLLECTION_SLUG = 'shop-collections' as const
export const BRAND_SLUG = 'brands' as const
export const ADDRESS_SLUG = 'address' as const
export const CUSTOMER_SLUG = 'customers' as const
export const CART_SLUG = 'cart' as const
export const TESTIMONIALS_SLUG = 'testimonials' as const
export const SPA_SLUG = 'spas' as const
export const GALLERIES_SLUG = 'galleries' as const
export const MEDIA_FOLDER_SLUG = 'media-folders' as const
export const SHIPPING_OPTION_SLUG = 'shipping-options' as const

export const MENTOR_SLUG = 'mentors' as const
export const STUDENT_SLUG = 'students' as const
